# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\cielo\\Downloads\\BLUE-master\\Dropthebeat'],
             binaries=[],
             datas=[('./Resource/_bg.jpg', './Resource'),
                     ('./Resource/image0.jpg', './Resource'),
                     ('./Resource/image1.jpg', './Resource'),
                     ('./Resource/image2.jpg', './Resource'),
                     ('./Resource/image3.jpg', './Resource'),
                     ('./Resource/main_background.jpg', './Resource'),
                     ('./Resource/_frame/_frame.png', './Resource/_frame'),
                     ('./Resource/_frame/_frame1.png', './Resource/_frame'),
                     ('./Resource/_frame/_frame2.png', './Resource/_frame'),
                     ('./Resource/_frame/_frame3.png', './Resource/_frame'),
                     ('./Resource/_frame/_frame4.png', './Resource/_frame'),
                     ('./Resource/_frame/_frame5.png', './Resource/_frame'),
                     ('./Resource/_frame/_frame6.png', './Resource/_frame'),
                     ('./Resource/_frame/_result.png', './Resource/_frame'),
                     ('./Resource/_icon/_back.png', './Resource/_icon'),
                     ('./Resource/_node/_node1.png', './Resource/_node'),
                     ('./Resource/_node/_node1_hover.png', './Resource/_node'),
                     ('./Resource/_node/_node2.png', './Resource/_node'),
                     ('./Resource/_node/_node2_hover.png', './Resource/_node'),
                     ('./Resource/_node/_node3.png', './Resource/_node'),
                     ('./Resource/_node/_node3_hover.png', './Resource/_node'),
                     ('./Resource/_node/_node4.png', './Resource/_node'),
                     ('./Resource/_node/_node4_hover.png', './Resource/_node'),
                     ('./Resource/_note/_note.png', './Resource/_note'),
                     ('./Resource/effect/*', './Resource/effect'),
                     ('./Resource/Font/CookieRun.ttf', './Resource/Font'),
                     ('./Resource/Font/digital.ttf', './Resource/Font'),
                     ('./Resource/Font/digital_n.ttf', './Resource/Font'),
                     ('./Resource/Font/interparkGothicOTFB.otf', './Resource/Font'),
                     ('./Resource/Font/interparkGothicOTFM.otf', './Resource/Font'),
                     ('./Resource/Font/SansJP.otf', './Resource/Font'),
                     ('./Songs/_dynamite.ogg', './Songs'),
                     ('./Songs/_dynamite.npy', './Songs'),
                     ('./Songs/_girl.mp3', './Songs'),
                     ('./Songs/_girl.npy', './Songs'),
                     ('./Songs/_hot air balloon.mp3', './Songs'),
                     ('./Songs/_hot air balloon.npy', './Songs'),
                     ('./Songs/_shelter.mp3', './Songs'),
                     ('./Songs/_shelter.npy', './Songs'),
                     ('./Sound/sound1.ogg', './Sound'),
                     ('./Sound/sound2.ogg', './Sound'),
                     ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='drop the beat',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')
